export const mockProducts = [
  {
    id: "1",
    nameKey: "productOnePiece",
    name: "Чохол на ID-картку 'One Piece'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням персонажів з аніме One Piece. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product1.jpeg",
    category: "id-cards",
    subcategory: "anime",
    colors: ["#8B4513", "#A52A2A", "#D2691E"],
    sku: "ID-OP-001",
  },
  {
    id: "2",
    nameKey: "productHelloKitty",
    name: "Чохол на ID-картку 'Hello Kitty'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням Hello Kitty. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product2.jpeg",
    category: "id-cards",
    subcategory: "cartoons",
    colors: ["#FF69B4", "#FFB6C1", "#FFC0CB"],
    sku: "ID-HK-001",
  },
  {
    id: "3",
    nameKey: "productBreakingBad",
    name: "Чохол на ID-картку 'Breaking Bad'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням персонажів з серіалу Breaking Bad. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product4.jpeg",
    category: "id-cards",
    subcategory: "movies",
    colors: ["#000000", "#8B4513", "#A52A2A"],
    sku: "ID-BB-001",
  },
  {
    id: "4",
    nameKey: "productNaruto",
    name: "Чохол на ID-картку 'Наруто'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням персонажів з аніме Наруто. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product3.jpeg",
    category: "id-cards",
    subcategory: "anime",
    colors: ["#FF4500", "#FFA500", "#FFD700"],
    sku: "ID-NAR-001",
  },
  {
    id: "5",
    nameKey: "productHarryPotter",
    name: "Чохол на ID-картку 'Гаррі Поттер'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням символів з Гаррі Поттера. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product1.jpeg",
    category: "id-cards",
    subcategory: "movies",
    colors: ["#000000", "#8B4513", "#A52A2A"],
    sku: "ID-HP-001",
  },
  {
    id: "6",
    nameKey: "productSimpsons",
    name: "Чохол на ID-картку 'Сімпсони'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням персонажів з мультсеріалу Сімпсони. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product2.jpeg",
    category: "id-cards",
    subcategory: "cartoons",
    colors: ["#FFD700", "#FFA500", "#FF4500"],
    sku: "ID-SIM-001",
  },
  {
    id: "7",
    nameKey: "productWitcher",
    name: "Чохол на ID-картку 'Відьмак'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням символів з серії ігор Відьмак. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product4.jpeg",
    category: "id-cards",
    subcategory: "games",
    colors: ["#000000", "#8B4513", "#A52A2A"],
    sku: "ID-WIT-001",
  },
  {
    id: "8",
    nameKey: "productPokemon",
    name: "Чохол на ID-картку 'Покемон'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням покемонів. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product3.jpeg",
    category: "id-cards",
    subcategory: "anime",
    colors: ["#FF4500", "#FFA500", "#FFD700"],
    sku: "ID-POK-001",
  },
  {
    id: "9",
    nameKey: "productFriends",
    name: "Чохол на ID-картку 'Друзі'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням символів з серіалу Друзі. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product1.jpeg",
    category: "id-cards",
    subcategory: "movies",
    colors: ["#000000", "#8B4513", "#A52A2A"],
    sku: "ID-FRI-001",
  },
  {
    id: "10",
    nameKey: "productRickAndMorty",
    name: "Чохол на ID-картку 'Рік і Морті'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням персонажів з мультсеріалу Рік і Морті. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product2.jpeg",
    category: "id-cards",
    subcategory: "cartoons",
    colors: ["#00BFFF", "#1E90FF", "#4169E1"],
    sku: "ID-RM-001",
  },
  {
    id: "11",
    nameKey: "productMinecraft",
    name: "Чохол на ID-картку 'Minecraft'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням символів з гри Minecraft. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product4.jpeg",
    category: "id-cards",
    subcategory: "games",
    colors: ["#8B4513", "#A52A2A", "#D2691E"],
    sku: "ID-MIN-001",
  },
  {
    id: "12",
    nameKey: "productAttackOnTitan",
    name: "Чохол на ID-картку 'Атака титанів'",
    description:
      "Шкіряний чохол на ID-картку з гравіюванням персонажів з аніме Атака титанів. Виготовлений з натуральної шкіри найвищої якості.",
    price: 299,
    image: "/images/product3.jpeg",
    category: "id-cards",
    subcategory: "anime",
    colors: ["#8B4513", "#A52A2A", "#D2691E"],
    sku: "ID-AOT-001",
  },
]
